name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        This form is for the Background browser extension, if you are using the VSCode desktop extension open an issue [here](https://github.com/KatsuteDev/Background/issues/new/choose). <br><br>

  - type: markdown
    attributes:
      value: |
        Before opening a bug report please check that your issue was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/BackgroundX/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2C%22critical+bug%22)

        Please also check that:

        * This is actually a bug and not a feature.
        * You are running the latest version.

        **If you are on Firefox and the addon does nothing, check the Permissions tab to make sure it's enabled.**

  - type: input
    attributes:
      label: Operating System
    validations:
      required: true

  - type: input
    attributes:
      label: Browser
    validations:
      required: true

  - type: dropdown
    attributes:
      label: IDE
      options:
        - Codespaces
        - github.dev
        - vscode.dev
    validations:
      required: true

  - type: input
    attributes:
      label: Extension Version
    validations:
      required: true

  - type: textarea
    id: settings
    attributes:
      label: Settings
      description: |
        Extension settings.

        Make sure to remove any sensitive information.

  - type: textarea
    attributes:
      label: Issue
      description: |
        Explain the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to replicate
      description: |
        Include steps to reproduce this issue. Add a video if possible.
    validations:
      required: true