name: Feature Request
description: Suggest a new feature
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request please check that your idea was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/BackgroundX/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22)

        Please also check that:

        * This feature makes sense for the project.
        * This feature does not already exist.
        * You are running the latest version.

        **This extension does not support loading local images; browsers do not allow this.**

        **This extension does not support converting local images to base64; extension settings do not have enough space to store this.**

        **Page refreshes are required for any options change; this extension doesn't support live changes.**

  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: |
        Explain your feature. Add any examples here.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: |
        Explain why you think this feature should be added.
    validations:
      required: true