name: Feature Request
description: Suggest a new feature
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |-
        **This extension is maintenance only and is no longer accepting feature requests.**

  - type: textarea
    attributes:
      label: .
    validations:
      required: false