name: Feature Request
description: Suggest a new feature
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        This form is for the Background browser extension, if you are using the VSCode desktop extension open an issue [here](https://github.com/KatsuteDev/Background/issues/new/choose). <br><br>

  - type: markdown
    attributes:
      value: |
        This extension is only receiving maintenance updates and is not accepting feature requests.
